import Header from "@/containers/Header";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import gsap from "gsap";
import { Intro } from "../containers/Intro";
const Home: NextPage = () => {
  return (
    <div className={"w-screen h-fit "}>
      <Head>
        <title>__ShivaMyneni__</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Intro />
    </div>
  );
};

export default Home;
